basePath: /
definitions:
  handler.HealthResponse:
    properties:
      message:
        type: string
      status:
        type: string
      timestamp:
        type: string
    type: object
  handler.HelloWorldRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  handler.HelloWorldResponse:
    properties:
      message:
        type: string
      timestamp:
        type: string
      version:
        type: string
    type: object
  services.HelloWorldMessage:
    properties:
      created_at:
        type: string
      id:
        type: integer
      message:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Go + Gin スタータープロジェクトのAPI仕様書
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Hello World API
  version: "1.0"
paths:
  /api/health:
    get:
      consumes:
      - application/json
      description: アプリケーションの健康状態を確認します
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.HealthResponse'
      summary: ヘルスチェック
      tags:
      - health
  /api/hello-world:
    get:
      consumes:
      - application/json
      description: 「Hello, World!」メッセージを返します
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.HelloWorldResponse'
      summary: Hello Worldを取得
      tags:
      - hello-world
    post:
      consumes:
      - application/json
      description: リクエストボディのJSONを受け取り、DBに保存してそのまま返します
      parameters:
      - description: リクエストボディ
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.HelloWorldRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.HelloWorldMessage'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: JSONを受け取り、DBに保存して返す
      tags:
      - hello-world
schemes:
- http
- https
swagger: "2.0"
