services:
  # テスト用PostgreSQL
  postgres-test:
    image: postgres:15-alpine
    container_name: hello-world-postgres-test
    environment:
      POSTGRES_DB: sampledb_test
      POSTGRES_USER: sampleuser
      POSTGRES_PASSWORD: samplepass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "15433:5432"  # テスト用ポート（15433）
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - hello-world-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sampleuser -d sampledb_test"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # テスト実行コンテナ
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hello-world-test-runner
    environment:
      NODE_ENV: test
      PORT: 8082
      HOST: 0.0.0.0
      DB_HOST: postgres-test
      DB_PORT: 5432
      DB_USER: sampleuser
      DB_PASSWORD: samplepass
      DB_NAME: sampledb_test
      DB_SSL: false
      MOCK_MODE: false
      RATE_LIMIT_ENABLED: false
      RATE_LIMIT_MAX: 1000
      RATE_LIMIT_WINDOW_MS: 900000
      LOG_LEVEL: error
      LOG_FORMAT: json
      CORS_ORIGIN: "*"
      CORS_CREDENTIALS: false
      CORS_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
      CORS_HEADERS: "Content-Type,Authorization"
      HELMET_ENABLED: true
      TRUST_PROXY: false
      REQUEST_SIZE_LIMIT: "10mb"
      API_PREFIX: "/api"
      API_VERSION: "v1"
      HEALTH_CHECK_PATH: "/api/health"
      HEALTH_CHECK_TIMEOUT: 5000
      SWAGGER_ENABLED: false
      SWAGGER_PATH: "/api-docs"
      SWAGGER_TITLE: "Hello World API (Test)"
      SWAGGER_VERSION: "1.0.0"
      JWT_SECRET: "test_jwt_secret_key_here"
      JWT_EXPIRES_IN: "24h"
    ports:
      - "8082:8082"
    depends_on:
      postgres-test:
        condition: service_healthy
    networks:
      - hello-world-test-network
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "test"]

volumes:
  postgres_test_data:
    driver: local

networks:
  hello-world-test-network:
    driver: bridge 